name: Project Name
title: Baked with Awestruct
org: Organization
base_url: ''

asciidoctor:
# enable compact after upgrade to Asciidoctor 0.1.2
#  :compact: true
  :eruby: erubis
  :attributes:
    idprefix: ''
    idseparator: '-'
    icons: ''


profiles:
  production:
    base_url: http://jasonbrooks.github.io/aweblog
    deploy:
      host: github_pages
      # use gh-branch for repositories other than <username>.github.io
      branch: gh-pages
      # use master branch for <username>.github.io repository
      #branch: master
  development:
     dev: true
     base_url: ''
